# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: test-registry
  namespace: openshift-operators
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: clair
      managed: false  # Disabled to save resources (vulnerability scanning)
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: false  # Using external Azure storage
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: false  # Disabled for testing (no autoscaling needed)
    - kind: route
      managed: true
    - kind: mirror
      managed: false  # Disabled for testing (repository mirroring not needed)
    - kind: monitoring
      managed: false  # Disabled for testing (metrics not critical)
    - kind: tls
      managed: true
    - kind: quay
      managed: true
    - kind: clairpostgres
      managed: false  # Disabled (not needed without clair)
