# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: openshift-operators
type: Opaque
stringData:
  config.yaml: |
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
    AUTHENTICATION_TYPE: Database
    DEFAULT_TAG_EXPIRATION: 2w
    ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
    FEATURE_BUILD_SUPPORT: false
    FEATURE_DIRECT_LOGIN: true
    FEATURE_MAILING: false
    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Red Hat Quay
    SETUP_COMPLETE: true
    TAG_EXPIRATION_OPTIONS:
    - 2w
    TEAM_RESYNC_STALE_TIME: 60m
    TESTING: false
    FEATURE_USER_INITIALIZE: true
    SUPER_USERS:
    - quayadmin
    DISTRIBUTED_STORAGE_CONFIG:
      azureStorage:
        - AzureStorage
        - azure_account_name: ${AZURE_STORAGE_ACCOUNT_NAME_PLACEHOLDER}
          azure_container: ${AZURE_STORAGE_CONTAINER_PLACEHOLDER}
          storage_path: /datastorage/registry
          azure_account_key: ${AZURE_STORAGE_ACCOUNT_KEY_PLACEHOLDER}
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
      - azureStorage
