# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: openshift-operators
type: Opaque
stringData:
  config.yaml: |
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
    AUTHENTICATION_TYPE: Database
    DEFAULT_TAG_EXPIRATION: 2w
    ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
    FEATURE_BUILD_SUPPORT: false
    FEATURE_DIRECT_LOGIN: true
    FEATURE_MAILING: false
    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Red Hat Quay
    SETUP_COMPLETE: true
    TAG_EXPIRATION_OPTIONS:
    - 2w
    TEAM_RESYNC_STALE_TIME: 60m
    TESTING: false
    FEATURE_USER_INITIALIZE: true
    SUPER_USERS:
    - quayadmin
    # ROSA uses S3 storage for better performance and reliability
    DISTRIBUTED_STORAGE_CONFIG:
      s3Storage:
        - S3Storage
        - host: ${S3_HOST_PLACEHOLDER}
          s3_access_key: ${AWS_ACCESS_KEY_ID_PLACEHOLDER}
          s3_secret_key: ${AWS_SECRET_ACCESS_KEY_PLACEHOLDER}
          s3_bucket: ${S3_BUCKET_NAME_PLACEHOLDER}
          s3_region: ${S3_REGION_PLACEHOLDER}
          storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
      - s3Storage