---
# Checkov configuration for ROSA Terraform
# Skip security checks that are acceptable for a testing/pipeline environment

skip-check:
  # Security Groups - Allow egress to 0.0.0.0/0
  - CKV_AWS_382  # Outbound internet access required for testing environment

  # RDS PostgreSQL - Testing environment configurations
  - CKV_AWS_226  # Auto minor version upgrades disabled to control upgrade timing in testing
  - CKV_AWS_129  # RDS logs not required for ephemeral testing database
  - CKV_AWS_293  # Deletion protection disabled for easier cleanup in testing environment
  - CKV_AWS_353  # Performance insights not required for testing environment
  - CKV_AWS_161  # IAM authentication not required for testing environment
  - CKV_AWS_157  # Multi-AZ disabled for cost savings in testing environment
  - CKV_AWS_118  # Enhanced monitoring not required for testing environment

  # ElastiCache Redis - Testing environment configurations
  - CKV_AWS_134  # ElastiCache backup not required for ephemeral testing cache

  # IAM - Quay S3 access requires programmatic credentials
  - CKV_AWS_273  # IAM user required for Quay programmatic S3 access (not SSO)
  - CKV_AWS_40   # IAM policy attached to user for Quay S3 access keys

  # Terraform Modules - Version pinning acceptable for testing
  - CKV_TF_1     # Terraform module version pins acceptable (commit hash not required for testing)
