# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: aro-eic-full-test-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"   # only PRs
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[./.tekton/tasks/git-clone.yaml]"
spec:
  pipelineRef:
    name: aro-eic-full-test-pipeline
  timeouts:
    pipeline: "336h"      # Total pipeline timeout (14 days)
    tasks: "335h"         # Individual task timeout (tasks + finally must be <= pipeline)
    finally: "60m"        # Finally tasks timeout
  params:
    - name: repoUrl
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: aroLocation
      value: "northeurope"
    - name: aroClusterName
      value: "sap-eic-validation"
    - name: aroVersion
      value: "4.19.20"
    - name: azureSecretName
      value: "azure-sp-secret"
    - name: pullSecretName
      value: "mj-pull-secret"
    - name: eicAuthSecretName
      value: "eic-auth-secret"
    - name: postgresAdminPasswordSecretName
      value: "azure-postgres-admin-password"
    - name: deployPostgres
      value: "false"
    - name: deployRedis
      value: "false"
    - name: publicDNS
      value: "false"
    - name: deployQuay
      value: "true"
    - name: quayAdminPasswordSecretName
      value: "quay-admin-secret"
    - name: jiraSecretName
      value: "jira-secret-mj"
    - name: jiraIssueKey
      value: "SAPOCP-1708"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 2Gi
