# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: endpoint-tests-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"   # only PRs
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
spec:
  pipelineRef:
    name: endpoint-test-pipeline
  params:
    - name: repoUrl
      value: "{{ repo_url }}"     # PaC fills with PR repo URL
    - name: revision
      value: "{{ revision }}"     # PaC fills with PR repo URL
    - name: clusterName   # ✏️ to be edited in each PR
      value: "<replace-me>"
    - name: authSecret    # ✏️ reference an existing secret
      value: "endpoint-auth"
    - name: ingressIp     # ✏️ to be edited in each PR
      value: "<replace-me>"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 10Mi
