# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sap-edge-external-services
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mjiao/sap-edge.git
    targetRevision: fix-redis-cert-argocd-test-mjiao-repo
    path: edge-integration-cell/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
