# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: endpoint-tests
spec:
  params:
    - name: clusterName
      type: string
    - name: authSecret
      type: string
    - name: ingressIp
      type: string
  workspaces:
    - name: basic-auth          # to mount the secret
  steps:
    - name: test-endpoints
      image: registry.access.redhat.com/ubi9/ubi
      env:
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.authSecret)
              key: auth_key        # key inside the Secret
        - name: INGRESS_IP                             # expose param to script
          value: $(params.ingressIp)
      script: |
        #!/usr/bin/env bash
        set -uo pipefail
        CLUSTER="$(params.clusterName)"
        HOST="eic.apps.${CLUSTER}.ocp.vslen"
        ENDPOINTS=(/http/test1 /http/testelster /slvredis /httpbinipfilter)
        failures=()
        for path in "${ENDPOINTS[@]}"; do
        echo "GET https://${HOST}${path}"
        if ! curl --fail --insecure --show-error -H "Authorization: Basic ${AUTH_KEY}" \
          "https://${HOST}${path}" --dump-header - --resolve "${HOST}:443:${INGRESS_IP}"; then
          failures+=("${path}")
        fi
        done
        if ((${#failures[@]})); then
        echo "Failed endpoints: ${failures[*]}"
        exit 1
        fi
