# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: endpoint-tests
spec:
  params:
    - name: clusterName
      type: string
    - name: authSecret
      type: string
    - name: ingressIp
      type: string
  workspaces:
    - name: source        # code from git-clone
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/ubi      # has bash
      workingDir: $(workspaces.source.path)
      env:
        - name: AUTH_KEY
          valueFrom: { secretKeyRef: { name: $(params.authSecret), key: auth_key } }
        - name: CLUSTER
          value: $(params.clusterName)
        - name: INGRESS_IP
          value: $(params.ingressIp)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        microdnf -y install make git >/dev/null 2>&1     # ensure make is present
        make test-endpoints
