# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: endpoint-tests
spec:
  params:
    - name: host
      type: string
      description: The full hostname to test.
    - name: authSecret
      type: string
      description: The name of the secret containing the auth key.
    - name: ingressIP
      type: string
      description: The Ingress IP for internal resolution.
      default: ""
    - name: publicDNS
      type: string
      description: Set to "true" to use public DNS instead of --resolve.
      default: "false"
  workspaces:
    - name: source        # code from git-clone
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/ubi      # has bash
      workingDir: $(workspaces.source.path)
      env:
        - name: AUTH_KEY
          valueFrom: { secretKeyRef: { name: $(params.authSecret), key: auth_key } }
        - name: INGRESS_IP
          value: $(params.ingressIP)
        - name: HOST
          value: $(params.host)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        dnf -y install make >/dev/null 2>&1   # ensure make is present
        make test-endpoints
