# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: endpoint-tests
spec:
  params:
    - name: host
      type: string
    - name: authSecret
      type: string
    - name: ingressIP
      type: string
      default: ""
    - name: publicDNS
      type: string
      default: "false"
    - name: endpointPath
      type: string
      description: The single endpoint path to test (e.g. /http/test1)
  workspaces:
    - name: source
  steps:
    - name: run-single-test
      image: registry.access.redhat.com/ubi9/ubi-minimal # Smaller image is sufficient
      workingDir: $(workspaces.source.path)
      env:
        - name: AUTH_KEY
          valueFrom: { secretKeyRef: { name: $(params.authSecret), key: auth_key } }
        - name: INGRESS_IP
          value: $(params.ingressIP)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        # Assuming the script is in the root of the repo, adjust if needed
        TEST_SCRIPT="./edge-integration-cell/test_eic_endpoints.sh"

        SCRIPT_ARGS=("--host" "$(params.host)")

        if [[ "$(params.publicDNS)" == "true" ]]; then
          SCRIPT_ARGS+=("--public-dns")
        fi

        if [[ ! -f "$TEST_SCRIPT" ]]; then
          echo "❌ Test script not found at $TEST_SCRIPT"
          exit 1
        fi
        chmod +x "$TEST_SCRIPT"

        # Pass the endpointPath as the final argument
        echo "▶️ Testing endpoint: $(params.endpointPath)"
        $TEST_SCRIPT "${SCRIPT_ARGS[@]}" "$(params.endpointPath)"