# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rate-limit-test
spec:
  description: >-
    This task tests an endpoint for a 429 rate limit exceeded error
    by calling it multiple times in quick succession.
  params:
    - name: clusterInfoSecretName
      type: string
    - name: endpointPath
      type: string
    - name: publicDNS
      type: string
      default: "false"
  workspaces:
    - name: source
  steps:
    - name: run-rate-limit-test
      image: registry.access.redhat.com/ubi9/ubi-minimal
      workingDir: $(workspaces.source.path)
      env:
        - name: HOST
          valueFrom: { secretKeyRef: { name: $(params.clusterInfoSecretName), key: host } }
        - name: INGRESS_IP
          valueFrom: { secretKeyRef: { name: $(params.clusterInfoSecretName), key: ingressIP } }
        - name: AUTH_KEY
          valueFrom: { secretKeyRef: { name: $(params.clusterInfoSecretName), key: authKey } }
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
       
        TEST_SCRIPT="./edge-integration-cell/rate-limit-test.sh"

        SCRIPT_ARGS=("--host" "$(params.host)")

        if [[ "$(params.publicDNS)" == "true" ]]; then
          SCRIPT_ARGS+=("--public-dns")
        fi

        if [[ ! -f "$TEST_SCRIPT" ]]; then
          echo "❌ Test script not found at $TEST_SCRIPT"
          exit 1
        fi
        chmod +x "$TEST_SCRIPT"
        
        echo "▶️ Running rate limit test for endpoint: $(params.endpointPath)"
        $TEST_SCRIPT "${SCRIPT_ARGS[@]}" "$(params.endpointPath)"