# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
resources:
  - redis_enterprise_cluster_ha.yaml
  - redis_enterprise_database.yaml
