# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-FileContributor: Kirill Satarin (@kksat)
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redb
  namespace: sap-eic-external-redis
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  redisEnterpriseCluster:
    name: rec
  tlsMode: enabled
