# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sap-eic-external-redis
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/mjiao/sap-edge.git
    targetRevision: fix-redis-cert-test-argocd
    path: edge-integration-cell/external-redis
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sap-eic-external-redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true
