# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: aro-edgelm-validation-pipeline
  annotations:
    description: "Edge LM validation pipeline: deploys ARO cluster with Quay storage only (no PostgreSQL/Redis), deploys Quay registry operator, and validates edgelm namespace pods"
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
    - name: aroLocation
      type: string
      description: "ARO location"
      default: "northeurope"
    - name: aroClusterName
      type: string
      description: "ARO cluster name"
    - name: aroVersion
      type: string
      description: "ARO version"
      default: "4.15.35"
    - name: azureSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Azure service principal credentials, ARO resource group, and ARO domain"
      default: "azure-sp-secret"
    - name: pullSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Red Hat pull secret"
      default: "redhat-pull-secret"
    - name: quayAdminPasswordSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Quay admin password and email"
      default: "quay-admin-secret"
    - name: jiraSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Jira credentials"
      default: ""
    - name: jiraIssueKey
      type: string
      description: "Jira issue key to update with deployment results"
      default: ""
    - name: skipEdgelmValidation
      type: string
      description: "Skip edgelm validation and Jira updates (true/false). Use 'true' for generic ARO testing."
      default: "false"
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef: { name: git-clone }
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source

    - name: deploy-aro
      runAfter: [fetch-repository]
      taskRef: { name: aro-deploy-with-eic-services }
      params:
        - name: aroLocation
          value: $(params.aroLocation)
        - name: aroClusterName
          value: $(params.aroClusterName)
        - name: aroVersion
          value: $(params.aroVersion)
        - name: azureSecretName
          value: $(params.azureSecretName)
        - name: pullSecretName
          value: $(params.pullSecretName)
        - name: postgresAdminPasswordSecretName
          value: "azure-postgres-admin-password"
        - name: deployPostgres
          value: "false"
        - name: deployRedis
          value: "false"
        - name: deployQuay
          value: "true"
      workspaces:
        - name: source
          workspace: source

    - name: validate-and-get-access
      runAfter: [deploy-aro]
      taskRef: { name: aro-validate-and-get-access }
      params:
        - name: aroClusterName
          value: $(params.aroClusterName)
        - name: azureSecretName
          value: $(params.azureSecretName)
        - name: postgresAdminPasswordSecretName
          value: "azure-postgres-admin-password"
      workspaces:
        - name: source
          workspace: source

    - name: deploy-quay
      runAfter: [validate-and-get-access]
      taskRef: { name: aro-quay-deploy }
      params:
        - name: aroClusterName
          value: $(params.aroClusterName)
        - name: azureSecretName
          value: $(params.azureSecretName)
        - name: quayAdminPasswordSecretName
          value: $(params.quayAdminPasswordSecretName)
      workspaces:
        - name: source
          workspace: source

    # Manual approval step after ARO and Quay deployment (only for edgelm validation)
    - name: manual-approval-post-deployment
      runAfter: [deploy-quay]
      when:
        - input: $(params.skipEdgelmValidation)
          operator: in
          values: ["false"]
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
        - name: approvers
          value:
            - mjiao
            - rbhandar
            - ksatarin
            - kube:admin
        - name: description
          value: "ARO cluster and Quay registry deployed successfully. Approve to proceed with Edge LM namespace pod validation."
        - name: numberOfApprovalsRequired
          value: '1'
        - name: timeout
          value: '336h'

    # Validate pods and generate deployment status report (only for edgelm validation)
    - name: deployment-status-report
      runAfter: [manual-approval-post-deployment]
      when:
        - input: $(params.skipEdgelmValidation)
          operator: in
          values: ["false"]
      taskRef: { name: aro-deployment-status-report }
      params:
        - name: aroClusterName
          value: $(params.aroClusterName)
        - name: azureSecretName
          value: $(params.azureSecretName)
        - name: namespace
          value: "edgelm"
        - name: expectedPodCount
          value: "3"
        - name: deploymentType
          value: "aro-edgelm-validation"
      workspaces:
        - name: source
          workspace: source

    # Manual approval before second round of validation
    - name: approval-second-validation-round
      runAfter: [deployment-status-report]
      when:
        - input: $(params.skipEdgelmValidation)
          operator: in
          values: ["false"]
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
        - name: approvers
          value:
            - mjiao
            - rbhandar
            - ksatarin
            - kube:admin
        - name: description
          value: |
            First round of edgelm pod validation completed.

            Cluster: $(params.aroClusterName)

            ✅ APPROVE: Run second round of edgelm pod validation
            ❌ REJECT: Skip second round and proceed
        - name: numberOfApprovalsRequired
          value: '1'
        - name: timeout
          value: '336h'

    # Second round of edgelm pod validation
    - name: deployment-status-report-round2
      runAfter: [approval-second-validation-round]
      when:
        - input: $(params.skipEdgelmValidation)
          operator: in
          values: ["false"]
      taskRef: { name: aro-deployment-status-report }
      params:
        - name: aroClusterName
          value: $(params.aroClusterName)
        - name: azureSecretName
          value: $(params.azureSecretName)
        - name: namespace
          value: "edgelm"
        - name: expectedPodCount
          value: "3"
        - name: deploymentType
          value: "aro-edgelm-validation"
      workspaces:
        - name: source
          workspace: source

    # Update Jira with deployment status (only for edgelm validation)
    - name: update-jira-deployment-status
      runAfter: [deployment-status-report-round2]
      when:
        - input: $(params.skipEdgelmValidation)
          operator: in
          values: ["false"]
      taskRef:
        name: jira-add-comment-custom
      params:
        - name: jiraSecretName
          value: $(params.jiraSecretName)
        - name: jiraIssueKey
          value: $(params.jiraIssueKey)
        - name: comment
          value: |
            h2. ✅ Edge LM Validation Pipeline Completed

            ARO cluster with Quay registry and edgelm namespace validation completed successfully.

            *Infrastructure Configuration:*
            * *Cluster Name:* $(params.aroClusterName)
            * *Location:* $(params.aroLocation)
            * *ARO Version:* $(params.aroVersion)
            * *External Services:* None (lightweight deployment)
            * *Use Case:* Edge LM validation with container registry

            *Deployment Status:*
            * Repository cloned: ✅
            * ARO cluster deployed: ✅ Completed
            * Master node scheduling enabled: ✅ Completed
            * Quay registry deployment: ✅ Completed
            * Azure storage for Quay: ✅ Configured
            * Certificate trust: ✅ Configured
            * Edgelm namespace validation (2 rounds): ✅ All Pods Running/Completed

            *Infrastructure Components:*
            * Lightweight ARO cluster (no PostgreSQL/Redis) ✅
            * Quay container registry with Azure storage ✅
            * Edge LM workload validated ✅

            *Pipeline Details:*
            * *Repository:* $(params.repoUrl)
            * *Revision:* $(params.revision)

            Ready for final approval or additional operations. The infrastructure is fully deployed and operational.

    # Final manual approval step before teardown (runs for both edgelm and generic testing)
    # When skipEdgelmValidation=true, upstream tasks are skipped and this runs directly after deploy-quay
    - name: manual-approval-final
      runAfter: [update-jira-deployment-status]
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
        - name: approvers
          value:
            - mjiao
            - rbhandar
            - ksatarin
            - kube:admin
        - name: description
          value: "ARO cluster and Quay registry are ready. Approve to tear down ARO cluster and Azure resources when testing is complete."
        - name: numberOfApprovalsRequired
          value: '1'
        - name: timeout
          value: '336h'

    # Teardown ARO cluster after approval
    - name: teardown-aro
      runAfter: [manual-approval-final]
      taskRef: { name: aro-teardown }
      params:
        - name: aroClusterName
          value: $(params.aroClusterName)
        - name: azureSecretName
          value: $(params.azureSecretName)
      workspaces:
        - name: source
          workspace: source
