# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: endpoint-test-pipeline
spec:
  params:
    - name: clusterName
    - name: authSecret
  workspaces:
    - name: basic-auth
  tasks:
    - name: endpoint-tests
      taskRef:
        name: endpoint-tests
      params:
        - name: clusterName
          value: $(params.clusterName)
        - name: authSecret
          value: $(params.authSecret)
        - name: ingressIp
          value: $(params.ingressIp)
      workspaces:
        - name: basic-auth
          workspace: basic-auth
