# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: endpoint-test-pipeline
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
    - name: clusterName
      type: string
    - name: authSecret
      type: string
    - name: ingressIp
      type: string
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef: { name: git-clone }
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: endpoint-tests
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: clusterName
          value: $(params.clusterName)
        - name: authSecret
          value: $(params.authSecret)
        - name: ingressIp
          value: $(params.ingressIp)
      workspaces:
        - name: source
          workspace: source