# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: endpoint-test-pipeline
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
    - name: host
      type: string
    - name: authSecret
      type: string
    - name: ingressIP
      type: string
      default: ""
    - name: publicDNS
      type: string
      default: "false"
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef: { name : git-clone }
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source

    - name: test-httpbinipfilter
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /httpbinipfilter
        - name: host
          value: $(params.host)
        - name: authSecret
          value: $(params.authSecret)
        - name: ingressIP
          value: $(params.ingressIP)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-http-test1
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /http/test1
        - name: host
          value: $(params.host)
        - name: authSecret
          value: $(params.authSecret)
        - name: ingressIP
          value: $(params.ingressIP)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-http-testelster
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /http/testelster
        - name: host
          value: $(params.host)
        - name: authSecret
          value: $(params.authSecret)
        - name: ingressIP
          value: $(params.ingressIP)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-slvredis
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /slvredis
        - name: host
          value: $(params.host)
        - name: authSecret
          value: $(params.authSecret)
        - name: ingressIP
          value: $(params.ingressIP)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source