# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: endpoint-test-pipeline
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
    - name: clusterConfigMapName
      type: string
    - name: eicAuthSecretName
      type: string
    - name: publicDNS
      type: string
      default: "false"
    - name: jiraSecretName
      type: string
    - name: jiraIssueKey
      type: string
    - name: extraInfo
      type: string
      default: ""
      description: "Extra information to include in the Jira ticket comment"
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef: { name : git-clone }
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source

    - name: test-httpbinipfilter
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /httpbinipfilter
        - name: clusterConfigMapName
          value: $(params.clusterConfigMapName)
        - name: eicAuthSecretName
          value:  $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-http-test1
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /http/test1
        - name: clusterConfigMapName
          value: $(params.clusterConfigMapName)
        - name: eicAuthSecretName
          value:  $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-http-testelster
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /http/testelster
        - name: clusterConfigMapName
          value: $(params.clusterConfigMapName)
        - name: eicAuthSecretName
          value:  $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-slvredis
      runAfter: [fetch-repository]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /slvredis
        - name: clusterConfigMapName
          value: $(params.clusterConfigMapName)
        - name: eicAuthSecretName
          value:  $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-ratelimit-slvredis
      runAfter: [ test-slvredis ]
      taskRef: { name: rate-limit-test }
      params:
        - name: endpointPath
          value: /slvredis
        - name: clusterConfigMapName
          value: $(params.clusterConfigMapName)
        - name: eicAuthSecretName
          value:  $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: update-jira-ticket
      runAfter:
        - test-httpbinipfilter
        - test-http-test1
        - test-http-testelster
        - test-slvredis
        - test-ratelimit-slvredis
      taskRef:
        name: jira-add-comment-custom
      params:
        - name: jiraSecretName
          value: $(params.jiraSecretName)
        - name: jiraIssueKey
          value: $(params.jiraIssueKey)
        - name: comment
          value: |
            h2. ✅ Endpoint Tests Passed

            All automated endpoint tests passed successfully.

            *Details:*
            * *Repository:* $(params.repoUrl)
            * *Revision:* $(params.revision)
            * *Target Cluster ConfigMap:* $(params.clusterConfigMapName)
            ${{ if ne(params.extraInfo, "") }}* *Extra Info:* $(params.extraInfo)${{ end }}

            *Executed Tests:* 
            * test-http-test1
            * test-http-testelster
            * test-httpbinipfilter
            * test-slvredis
            * test-ratelimit-slvredis