# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rosa-eic-full-test-pipeline
  annotations:
    description: "Complete SAP Edge Integration Cell validation pipeline for ROSA: deploys ROSA HCP with AWS services (RDS PostgreSQL, ElastiCache Redis, S3 for Quay via Terraform), Quay registry operator, runs comprehensive endpoint tests, and tears down infrastructure"
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
    - name: clusterName
      type: string
      description: "ROSA cluster name (max 15 characters)"
    - name: awsRegion
      type: string
      description: "AWS region"
      default: "eu-north-1"
    - name: rosaVersion
      type: string
      description: "ROSA version"
      default: "4.17.0"
    - name: awsSecretName
      type: string
      description: "Name of the Kubernetes Secret containing AWS credentials"
      default: "aws-credentials-secret"
    - name: redhatTokenSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Red Hat OCM token"
      default: "redhat-token-secret"
    - name: eicAuthSecretName
      type: string
      description: "EIC authentication secret name"
    - name: postgresAdminPasswordSecretName
      type: string
      description: "Name of the Kubernetes Secret containing PostgreSQL admin password"
      default: "rosa-postgres-admin-password"
    - name: quayAdminPasswordSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Quay admin password and email"
      default: "quay-admin-secret"
    - name: deployPostgres
      type: string
      description: "Whether to deploy RDS PostgreSQL (true/false)"
      default: "true"
    - name: deployRedis
      type: string
      description: "Whether to deploy ElastiCache Redis (true/false)"
      default: "true"
    - name: deployQuay
      type: string
      description: "Whether to deploy S3 for Quay (true/false)"
      default: "true"
    - name: publicDNS
      type: string
      description: "Use public DNS"
      default: "false"
    - name: terraformStateS3Bucket
      type: string
      description: "S3 bucket name for Terraform state storage"
      default: "eic-test-rosa-terraform-state"
    - name: terraformStateS3Key
      type: string
      description: "S3 key for Terraform state file (auto-generated as rosa/${CLUSTER_NAME}/terraform.tfstate)"
      default: "rosa/terraform.tfstate"
    - name: terraformStateDynamoDBTable
      type: string
      description: "DynamoDB table for Terraform state locking"
      default: "eic-test-rosa-terraform-state-lock"
    - name: jiraSecretName
      type: string
      description: "Name of the Kubernetes Secret containing Jira credentials"
    - name: jiraIssueKey
      type: string
      description: "Jira issue key to update with test results"
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef: { name: git-clone }
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
        - name: depth
          value: "0"  # Full clone to ensure all refs are available
      workspaces:
        - name: output
          workspace: source

    - name: deploy-rosa
      runAfter: [fetch-repository]
      taskRef: { name: rosa-deploy-with-eic-services }
      params:
        - name: clusterName
          value: $(params.clusterName)
        - name: awsRegion
          value: $(params.awsRegion)
        - name: rosaVersion
          value: $(params.rosaVersion)
        - name: awsSecretName
          value: $(params.awsSecretName)
        - name: redhatTokenSecretName
          value: $(params.redhatTokenSecretName)
        - name: postgresAdminPasswordSecretName
          value: $(params.postgresAdminPasswordSecretName)
        - name: deployPostgres
          value: $(params.deployPostgres)
        - name: deployRedis
          value: $(params.deployRedis)
        - name: deployQuay
          value: $(params.deployQuay)
        - name: terraformStateS3Bucket
          value: $(params.terraformStateS3Bucket)
        - name: terraformStateS3Key
          value: $(params.terraformStateS3Key)
        - name: terraformStateDynamoDBTable
          value: $(params.terraformStateDynamoDBTable)
      workspaces:
        - name: source
          workspace: source

    - name: validate-and-get-access
      runAfter: [deploy-rosa]
      taskRef: { name: rosa-validate-and-get-access }
      params:
        - name: clusterName
          value: $(params.clusterName)
        - name: awsRegion
          value: $(params.awsRegion)
        - name: awsSecretName
          value: $(params.awsSecretName)
        - name: redhatTokenSecretName
          value: $(params.redhatTokenSecretName)
        - name: postgresAdminPasswordSecretName
          value: $(params.postgresAdminPasswordSecretName)
        - name: terraformStateS3Bucket
          value: $(params.terraformStateS3Bucket)
        - name: terraformStateS3Key
          value: $(params.terraformStateS3Key)
        - name: terraformStateDynamoDBTable
          value: $(params.terraformStateDynamoDBTable)
      workspaces:
        - name: source
          workspace: source

    - name: deploy-quay
      runAfter: [validate-and-get-access]
      taskRef: { name: rosa-quay-deploy }
      params:
        - name: clusterName
          value: $(params.clusterName)
        - name: s3BucketName
          value: "$(params.clusterName)-quay-registry"  # Will be retrieved from Terraform
        - name: s3Region
          value: $(params.awsRegion)
        - name: s3Host
          value: "s3.$(params.awsRegion).amazonaws.com"
        - name: awsSecretName
          value: $(params.awsSecretName)
        - name: quayAdminPasswordSecretName
          value: $(params.quayAdminPasswordSecretName)
        - name: redhatTokenSecretName
          value: $(params.redhatTokenSecretName)
      workspaces:
        - name: source
          workspace: source

    # Single approval gate - Approve to run tests, Reject to skip tests and teardown
    - name: approval-run-tests
      runAfter: [deploy-quay]
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
        - name: approvers
          value:
            - mjiao
            - rbhandar
            - ksatarin
        - name: description
          value: |
            ROSA cluster, AWS services (RDS PostgreSQL, ElastiCache Redis, S3), and Quay registry are deployed.
            
            ✅ APPROVE: Run EIC endpoint tests, then wait for teardown approval
            ❌ REJECT: Skip tests and proceed directly to teardown
        - name: numberOfApprovalsRequired
          value: '1'
        - name: timeout
          value: '168h'

    - name: test-httpbinipfilter
      runAfter: [approval-run-tests]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /httpbinipfilter
        - name: clusterConfigMapName
          value: "cluster-info-rosa-$(params.clusterName)"
        - name: eicAuthSecretName
          value: $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-http-test1
      runAfter: [approval-run-tests]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /http/test1
        - name: clusterConfigMapName
          value: "cluster-info-rosa-$(params.clusterName)"
        - name: eicAuthSecretName
          value: $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-http-testelster
      runAfter: [approval-run-tests]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /http/testelster
        - name: clusterConfigMapName
          value: "cluster-info-rosa-$(params.clusterName)"
        - name: eicAuthSecretName
          value: $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-slvredis
      runAfter: [approval-run-tests]
      taskRef: { name: endpoint-tests }
      params:
        - name: endpointPath
          value: /slvredis
        - name: clusterConfigMapName
          value: "cluster-info-rosa-$(params.clusterName)"
        - name: eicAuthSecretName
          value: $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: test-ratelimit-slvredis
      runAfter: [test-slvredis]
      taskRef: { name: rate-limit-test }
      params:
        - name: endpointPath
          value: /slvredis
        - name: clusterConfigMapName
          value: "cluster-info-rosa-$(params.clusterName)"
        - name: eicAuthSecretName
          value: $(params.eicAuthSecretName)
        - name: publicDNS
          value: $(params.publicDNS)
      workspaces:
        - name: source
          workspace: source

    - name: update-jira-ticket
      runAfter:
        - test-httpbinipfilter
        - test-http-test1
        - test-http-testelster
        - test-slvredis
        - test-ratelimit-slvredis
      taskRef:
        name: jira-add-comment-custom
      params:
        - name: jiraSecretName
          value: $(params.jiraSecretName)
        - name: jiraIssueKey
          value: $(params.jiraIssueKey)
        - name: comment
          value: |
            h2. ✅ Complete EIC Validation Pipeline Completed (ROSA)

            ROSA HCP cluster with full EIC infrastructure and all automated endpoint tests completed successfully.

            *Infrastructure Configuration:*
            * *Cluster Name:* $(params.clusterName)
            * *AWS Region:* $(params.awsRegion)
            * *ROSA Version:* $(params.rosaVersion)
            * *RDS PostgreSQL:* $(params.deployPostgres) (VPC private, Terraform-managed)
            * *ElastiCache Redis:* $(params.deployRedis) (VPC private, Terraform-managed)
            * *S3 for Quay:* $(params.deployQuay) (Encrypted, Terraform-managed)
            * *Quay Registry:* ✅ Deployed

            *Pipeline Status:*
            * Repository cloned: ✅
            * ROSA deployment with AWS services: ✅ Completed
            * Quay registry deployment: ✅ Completed
            * Validation and access setup: ✅ Completed
            * Endpoint tests: ✅ All Passed

            *Pipeline Details:*
            * *Repository:* $(params.repoUrl)
            * *Revision:* $(params.revision)
            * *Public DNS:* $(params.publicDNS)

            *Executed Tests:*
            * test-httpbinipfilter ✅
            * test-http-test1 ✅
            * test-http-testelster ✅
            * test-slvredis ✅
            * test-ratelimit-slvredis ✅

            *Infrastructure Components:*
            * ROSA HCP OpenShift cluster ✅
            * AWS RDS PostgreSQL (VPC private) ✅
            * AWS ElastiCache Redis (VPC private) ✅
            * S3 bucket for Quay registry ✅
            * All EIC endpoints validated ✅

            *Security:*
            * RDS PostgreSQL: Private connectivity via VPC security groups (Terraform-managed)
            * ElastiCache Redis: Private access within VPC (Terraform-managed)
            * S3 Storage: Encrypted with IAM user permissions (Terraform-managed)
            * Quay: Certificate trust configured for OpenShift integration

            Ready for manual teardown approval. The complete EIC infrastructure will be destroyed once approved.

    # Manual approval step before teardown - this will pause the pipeline
    - name: approval-teardown
      runAfter:
        - update-jira-ticket
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
        - name: approvers
          value:
            - mjiao
            - rbhandar
            - ksatarin
        - name: description
          value: |
            All endpoint tests completed. Please review results. 
            
            ✅ APPROVE: Tear down ROSA cluster and AWS resources
            ❌ REJECT: Keep cluster running (will timeout after 168h and teardown anyway)
        - name: numberOfApprovalsRequired
          value: '1'
        - name: timeout
          value: '168h'

    # Teardown after approval
    - name: teardown-rosa
      runAfter: [approval-teardown]
      taskRef: { name: rosa-teardown }
      params:
        - name: clusterName
          value: $(params.clusterName)
        - name: awsRegion
          value: $(params.awsRegion)
        - name: awsSecretName
          value: $(params.awsSecretName)
        - name: redhatTokenSecretName
          value: $(params.redhatTokenSecretName)
        - name: terraformStateS3Bucket
          value: $(params.terraformStateS3Bucket)
        - name: terraformStateDynamoDBTable
          value: $(params.terraformStateDynamoDBTable)
      workspaces:
        - name: source
          workspace: source
