# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: aro-quay-deployment-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"   # only PRs
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
spec:
  pipelineRef:
    name: aro-quay-deployment-pipeline
  timeouts:
    pipeline: "168h"      # Total pipeline timeout (7 days)
    tasks: "120m"         # Individual task timeout (2 hours)
    finally: "30m"        # Finally tasks timeout
  params:
    - name: repoUrl
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: aroLocation
      value: "northeurope"
    - name: aroClusterName
      value: "sapelm-quay"
    - name: aroVersion
      value: "4.17.27"
    - name: azureSecretName
      value: "azure-sp-secret"
    - name: pullSecretName
      value: "mj-pull-secret"
    - name: quayAdminPasswordSecretName
      value: "quay-admin-secret"
    - name: jiraSecretName
      value: "jira-secret-mj"
    - name: jiraIssueKey
      value: "SAPOCP-1659"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 200Mi