# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: aro-endpoint-test-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"   # only PRs
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
spec:
  pipelineRef:
    name: aro-endpoint-test-pipeline
  timeout: 168h
  params:
    - name: repoUrl
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: aroLocation
      value: "northeurope"
    - name: aroClusterName
      value: "sapeic"
    - name: aroVersion
      value: "4.17.27"
    - name: azureSecretName
      value: "azure-sp-secret"
    - name: pullSecretName
      value: "mj-pull-secret"
    - name: eicAuthSecretName
      value: "eic-auth-secret"
    - name: postgresAdminPasswordSecretName
      value: "azure-postgres-admin-password"
    - name: deployPostgres
      value: "true"
    - name: deployRedis
      value: "true"
    - name: publicDNS
      value: "false"
    - name: jiraSecretName
      value: "jira-secret-mj"
    - name: jiraIssueKey
      value: "SAPOCP-1590"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 10Mi
