# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hcp-kubevirt-validation-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineRef:
    name: hcp-kubevirt-validation-pipeline
  timeouts:
    pipeline: "168h"      # Total pipeline timeout (7 days)
    tasks: "120m"         # Individual task timeout (2 hours)
    finally: "30m"        # Finally tasks timeout
  params:
    - name: repoUrl
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: hostedClusterName
      value: "hcp-eic-test"
    - name: hostedClusterNamespace
      value: "clusters"
    - name: releaseImage
      value: "quay.io/openshift-release-dev/ocp-release:4.19.0-x86_64"
    - name: nodePoolReplicas
      value: "3"
    - name: nodePoolCpuCores
      value: "16"
    - name: nodePoolMemoryGB
      value: "32"
    - name: rootDiskSizeGB
      value: "120"
    - name: pullSecretName
      value: "mj-pull-secret"
    - name: etcdStorageClass
      value: ""
    - name: postgresVersion
      value: "v15"
    - name: redisClusterType
      value: "standard"
    - name: jiraSecretName
      value: ""
    - name: jiraIssueKey
      value: ""
    - name: skipTeardown
      value: "false"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 200Mi
