# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hcp-kubevirt-validation-pr{{ pull_request_number }}-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"   # only PRs
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[./.tekton/tasks/git-clone.yaml]"
spec:
  pipelineRef:
    name: hcp-kubevirt-validation-pipeline
  timeouts:
    pipeline: "336h"      # Total pipeline timeout (14 days)
    tasks: "335h"         # Individual task timeout (tasks + finally must be <= pipeline)
    finally: "60m"        # Finally tasks timeout
  params:
    - name: repoUrl
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: hostedClusterName
      value: "hcp-eic-test"
    - name: hostedClusterNamespace
      value: "clusters"
    - name: releaseImage
      value: "quay.io/openshift-release-dev/ocp-release:4.19.0-x86_64"
    - name: nodePoolReplicas
      value: "3"
    - name: nodePoolCpuCores
      value: "16"
    - name: nodePoolMemoryGB
      value: "32"
    - name: rootDiskSizeGB
      value: "120"
    - name: pullSecretName
      value: "mj-pull-secret"
    - name: etcdStorageClass
      value: ""
    - name: postgresVersion
      value: "v15"
    - name: redisClusterType
      value: "standard"
    - name: eicAuthSecretName
      value: "eic-auth-secret"
    - name: publicDNS
      value: "false"
    - name: jiraSecretName
      value: "jira-secret-mj"
    - name: jiraIssueKey
      value: "SAPOCP-1945"
    - name: skipTeardown
      value: "false"
    - name: hubKubeconfigSecretName
      value: "hub-admin-kubeconfig"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 2Gi
