# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: endpoint-tests-hockenheim-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"   # only PRs
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
spec:
  pipelineRef:
    name: endpoint-test-pipeline
  params:
    - name: repoUrl
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: clusterConfigMapName
      value: "cluster-info-hockenheim"
    - name: eicAuthSecretName
      value: "eic-auth-secret"
    - name: publicDNS
      value: "false"
    - name: jiraSecretName
      value: "jira-secret-mj"
    - name: jiraIssueKey
      value: "SAPOCP-1638"
    - name: extraInfo
      value: "Current EIC version 8.32.3"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteMany]
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 10Mi
