# SPDX-FileCopyrightText: 2025 SAP edge team
# SPDX-FileContributor: Manjun Jiao (@mjiao)
# SPDX-FileContributor: Kirill Satarin (@kksat)
#
# SPDX-License-Identifier: Apache-2.0

---
name: Auto-approve Validation PRs

"on":
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check if all changed files are PipelineRun resources
        id: check-pipelinerun-only
        run: |
          # Get list of modified files using GitHub API approach
          FILES=""
          # First try using git merge-base to find the common ancestor
          if [[ -n "${{ github.event.pull_request.base.ref }}" ]]; then
            echo "Fetching base branch: ${{ github.event.pull_request.base.ref }}"
            git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }} 2>/dev/null || true
            # Try to find merge base and get diff
            MERGE_BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }} 2>/dev/null || echo "")
            if [[ -n "$MERGE_BASE" ]]; then
              FILES=$(git diff --name-only $MERGE_BASE HEAD 2>/dev/null || echo "")
              echo "Using merge-base approach: $MERGE_BASE"
            fi
          fi

          # Fallback: if merge-base failed, try with origin/main
          if [[ -z "$FILES" ]]; then
            echo "Merge-base failed, trying origin/main..."
            git fetch origin main:refs/remotes/origin/main 2>/dev/null || true
            FILES=$(git diff --name-only origin/main HEAD 2>/dev/null || echo "")
          fi

          # Final fallback: check recent commits
          if [[ -z "$FILES" ]]; then
            echo "All previous methods failed, checking recent commits..."
            FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "")
          fi

          # If no files found at all, assume no changes
          if [[ -z "$FILES" ]]; then
            echo "No files found to check"
            echo "all_pipelinerun=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Files to check: $FILES"

          # Check if ALL files are PipelineRun resources
          ALL_PIPELINERUN=true
          for file in $FILES; do
            echo "Checking file: $file"
            # Get file content
            FILE_CONTENT=""
            if [[ -f "$file" ]]; then
              FILE_CONTENT=$(cat "$file")
            elif [[ -n "${{ github.event.pull_request.head.sha }}" ]]; then
              FILE_CONTENT=$(git show ${{ github.event.pull_request.head.sha }}:$file 2>/dev/null || echo "")
            else
              FILE_CONTENT=$(git show HEAD:$file 2>/dev/null || echo "")
            fi

            # Check if this file is a PipelineRun resource
            if [[ -z "$FILE_CONTENT" ]] || ! echo "$FILE_CONTENT" | grep -E "^kind:\s*PipelineRun\s*$" > /dev/null; then
              echo "File $file is NOT a PipelineRun resource"
              ALL_PIPELINERUN=false
              break
            else
              echo "File $file is a PipelineRun resource ✓"
            fi
          done

          if [[ "$ALL_PIPELINERUN" == "true" ]]; then
            echo "All changed files are PipelineRun resources"
            echo "all_pipelinerun=true" >> $GITHUB_OUTPUT
          else
            echo "Not all changed files are PipelineRun resources"
            echo "all_pipelinerun=false" >> $GITHUB_OUTPUT
          fi


      - name: Auto-approve if conditions met
        if: >-
          startsWith(github.event.pull_request.title, '[Validation]') &&
          contains(fromJSON('["mjiao", "kksat", "RishabhKodes"]'), github.event.pull_request.user.login) &&
          steps.check-pipelinerun-only.outputs.all_pipelinerun == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}


      - name: Validate PR requirements
        if: >-
          startsWith(github.event.pull_request.title, '[Validation]') &&
          contains(fromJSON('["mjiao", "kksat", "RishabhKodes"]'), github.event.pull_request.user.login)
        run: |
          if [[ "${{ steps.check-pipelinerun-only.outputs.all_pipelinerun }}" == "false" ]]; then
            echo "❌ PR validation failed: Not all changed files are PipelineRun resources"
            echo "This PR must only modify PipelineRun resource files"
            exit 1
          fi

          echo "✅ PR validation passed"
          echo "All requirements met:"
          echo "- All changed files are PipelineRun resources: ${{ steps.check-pipelinerun-only.outputs.all_pipelinerun }}"
